 language: ruby
 rvm: "2.0.0"
 bundler_args: --without production
# uncomment this line if your project needs to run something other than `rake`:
 script: 
 - bin/rake db:migrate RAILS_ENV=test
 - bundle exec rspec spec